services:
  # Node.js Express application
  backend-nodejs:
    build: ./nodejs
    container_name: backend-nodejs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network


  # nginx proxy manager
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"  # http traffic
      - '443:443'    # HTTPS traffic
      - '5001:81'      # Admin web interface
    volumes: # place to store all the data that we need persistant and external
      - ./nodejs:/nodejs
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
